abstract final class AppRoutes {
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const businessSetup = '/business-setup';
  static const dashboard = '/dashboard';
  static const customers = '/customers';
  static const customerAdd = '/customer/add';
  static const customerEdit = '/customer/edit';
  static const customerDetails = '/customer/details';
  static const products = '/products';
  static const productAdd = '/product/add';
  static const productEdit = '/product/edit';
  static const productDetails = '/product/details';
  static const invoices = '/invoices';
  static const invoiceCreate = '/invoice/create';
  static const invoiceItemPicker = '/invoice/item-picker';
  static const invoiceDetails = '/invoice/details';
  static const invoicePreview = '/invoice/preview';
  static const quotations = '/quotations';
  static const quotationCreate = '/quotation/create';
  static const reports = '/reports';
  static const settings = '/settings';
  static const unitSettings = '/settings/units';
  static const more = '/more';
  static const backup = '/backup';
}
